### ISSUE TITLE
404 error when clicking on link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by SeanCraig** [nhsuk/frontend-library#51]
## What is the issue?
Clicking on the link to the PULL_REQUEST_TEMPLATE in the Getting Started section on https://github.com/nhsuk/frontend-library/blob/master/CONTRIBUTING.md results in a 404

### What did you expect to happen?
I expected it to open the PULL_REQUEST_TEMPLATE at https://github.com/nhsuk/frontend-library/blob/master/.github/PULL_REQUEST_TEMPLATE.md

### What did actually happen?
I got a 404 error

## What steps are required to reproduce the issue? 
Go to https://github.com/nhsuk/frontend-library/blob/master/CONTRIBUTING.md
Click on the link to the PULL_REQUEST_TEMPLATE in the Getting Started section 
results in a 404

## What was the environment where this issue occurred?
* Device: Windows Surface Pro 4
* Operating System: Windows 10
* Browser: Google Chrome
* Browser version: 62.0.3202.94 (Official Build) (64-bit)

**Comment by SeanCraig** [comment]
I think
`[PULL_REQUEST_TEMPLATE](./github/PULL_REQUEST_TEMPLATE.md). `
should be 
`[PULL_REQUEST_TEMPLATE](./.github/PULL_REQUEST_TEMPLATE.md). `

**Comment by st3v3nhunt** [comment]
Thanks @SeanCraig. Do you want to submit a PR with the change? If not I can do it.

**Comment by SeanCraig** [comment]
I'll give it a go. Need to set up git on my corp machine but worthwhile anyway. If I fail miserably I'll ask for help

**Comment by st3v3nhunt** [comment]
For something like this (adding a period to a markdown file) you could use the [browser editor](https://help.github.com/articles/editing-files-in-your-repository/). Just don't forget the emoji on the commit 😉
